### ISSUE TITLE
Feature request: PyPI?

### ISSUE THREAD

**Issue by ralokt** [gwu-libraries/django-profiles#1]
Hello,
As someone who is currently refactoring an old Django project to use Django 1.8, it would be awesome if these modifications were added to PyPI (especially for better interaction with things like `pip freeze`). I'd do it myself, but that would make me the owner of the new package, and I'd prefer if proper credit were given.

**Comment by ralokt** [comment]
OK, never mind, I just saw that `https://docs.djangoproject.com/en/1.4/topics/auth/#storing-additional-information-about-users` was removed in all versions of django that are still supported; I guess that makes `django-profiles` completely obsolete. Sorry for the hassle.

**Comment by kerchner** [comment]
@dchud It looks like this repo is obselete.  Shall we delete it or somehow archive it?

**Comment by ralokt** [comment]
I can imagine that it could still be useful to people who upgrade their django version one at a time (which might be a good idea, or at least, going from 1.2 to 1.8 is quite annoying, as I'm finding out).

**Comment by ralokt** [comment]
Actually... Now using this code in my Django 1.8 project with minor changes after reading

http://deathofagremmie.com/2014/05/24/retiring-get-profile-and-auth-profile-module/

I'd be glad to clean my changes up and submit a patch, if wanted.
